### ISSUE TITLE
Crash on snap/animate to cell

### ISSUE THREAD

**Issue by tylerwilson** [oleksandrbalan/lazytable#28]
Good day,

I am using code very similar what is shown in [here](https://github.com/oleksandrbalan/lazytable/issues/9) but I get a crash when I call the snapToCell (or animateToCell) method, like so:

`kotlin.UninitializedPropertyAccessException: lateinit property positionProvider has not been initialized
	at eu.wewox.minabox.MinaBoxState.getPositionProvider(MinaBoxState.kt:53)
	at eu.wewox.lazytable.LazyTableState.getPositionProvider(LazyTableState.kt:53)
	at eu.wewox.lazytable.LazyTableState.getCellOffset-xEiAX8E(LazyTableState.kt:105)
	at eu.wewox.lazytable.LazyTableState.animateToCell(LazyTableState.kt:74)
	at eu.wewox.lazytable.LazyTableState.animateToCell$default(LazyTableState.kt:67)
	at com.salonbiz.library.views.FindTimesViewKt$FindTimesView$3$1.invokeSuspend(FindTimesView.kt:66)`

I am unsure if I missing something, but it appears it should be creating the minabox.positionProvider, but it is not, hence the crash. 

Any and all help appreciated. Thank you!

Using LazyTable 1.8.0 with Compose multi-platform 1.6.1.

**Comment by JannisGehrt** [comment]
You probably solved the issue by now, but I'm leaving this here in case other people also encounter that problem:
This error occurs if you try to snap/animate before the table has been drawn. A better way to handle this is to use the `initialOffset` property when initialising the state with `rememberLazyTableState`.
Just to be sure that no crash occurs, I also wrapped any animations inside a try...catch block.
