### ISSUE TITLE
Crash with Compose 1.5.0-beta01

### ISSUE THREAD

**Issue by Tgo1014** [oleksandrbalan/lazytable#4]
When trying to add a `LazyTable` the app crashes with:

```
java.lang.AbstractMethodError: abstract method "void androidx.compose.foundation.lazy.layout.LazyLayoutItemProvider.Item(int, java.lang.Object, androidx.compose.runtime.Composer, int)"
 at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt$SkippableItem$1.invoke(LazyLayoutItemContentFactory.kt:138)
 at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt$SkippableItem$1.invoke(LazyLayoutItemContentFactory.kt:137)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
 at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
 at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
 at androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.SaveableStateProvider(LazySaveableStateHolder.kt:84)
 at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:137)
 at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.access$SkippableItem-JVlU9Rs(LazyLayoutItemContentFactory.kt:1)                                                                                     	
```

**Comment by GuilhE** [comment]
Having the same problem 😞

**Comment by GuilhE** [comment]
I believe this fixes this issue: https://github.com/oleksandrbalan/minabox/pull/8

**Comment by Tgo1014** [comment]
@GuilhE Thanks! I'll give it a try later 🙏🏽

**Comment by Tgo1014** [comment]
Thanks for your work @GuilhE! Great stuff!

**Comment by oleksandrbalan** [comment]
@GuilhE Thank you for your time and PR, it indeed fixes the problem, but I am planning to move to Compose Multiplatform, which is now capped on Compose 1.4.3. You could fork the library and update it for your needs, as I do not plan to publish also beta library versions.

When the new Compose Multiplatform version will be release I will release a new version with your fix.

**Comment by GuilhE** [comment]
> @GuilhE how yo fix the issue? You write about not this project and share the link not for this repo. 

Check this: https://github.com/oleksandrbalan/minabox/pull/8#issuecomment-1641768481

**Comment by oleksandrbalan** [comment]
Should be fixed now with new [1.5.0](https://github.com/oleksandrbalan/lazytable/releases/tag/v1.5.0) release.
